I added sasl.mechanism, and sasl.jaas.config for each cluster. and fix some bugs [#528, #513,#502,#479,#477,#471]
yahoo/CMAK pull request #532
Opened 2018-07-16 10:23 UTC by kingmorning

Hi 
I added sasl.mechanism, and sasl.jaas.config for each cluster. and fix some bugs [#528, #513,#502,#479,#477,#471]
I tested this new functions, mechanism includes PLAIN,GSSAPI,SCRAM-SHA-256,SCRAM-SHA-512.
and sasl.jaas.config is a optional string, such as: "org.apache.kafka.common.security.plain.PlainLoginModule required  username=kafka  password=kakafkaa;"

2018-07-16 10:23 UTC, yahoocla commented
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

2018-07-17 14:16 UTC, JasonFJ40 commented
Thank you @kingmorning!  My SSL issues have been solved!

2018-07-17 15:43 UTC, patelh requested changes

2018-07-17 15:43 UTC, patelh commented on app/controllers/Cluster.scala
> +      , "saslMechanism" -> nonEmptyText.verifying(validateSASLmechanism)
why is this field required?  If I am not using SASL, then why would we want the user to fill this in.

2018-07-17 15:43 UTC, patelh commented on app/kafka/manager/actor/cluster/KafkaStateActor.scala
> +    props.put(SaslConfigs.SASL_MECHANISM, config.clusterContext.config.saslMechanism.stringId)
We should only put sasl properties if cluster is configured for it.

2018-07-17 15:43 UTC, patelh commented on app/kafka/manager/KafkaManager.scala
> +                    saslMechanism: String,
This should be optional.  e.g. Option[String]

2018-07-17 15:43 UTC, patelh commented on app/kafka/manager/actor/cluster/KafkaStateActor.scala
> +    if (!clusterContext.config.jaasConfig.isEmpty) {
We should only put sasl properties if cluster is configured for it.

2018-07-17 15:43 UTC, patelh commented on app/kafka/manager/actor/cluster/KafkaStateActor.scala
> +                consumerProperties.put(SaslConfigs.SASL_MECHANISM, kaConfig.clusterContext.config.saslMechanism.stringId)
We should only put sasl properties if cluster is configured for it.

2018-07-17 15:45 UTC, patelh commented
Thanks for your contribution @kingmorning , let's make this change so SASL is optional and not required.

2018-07-23 18:17 UTC, patelh commented
If you need help making the changes, please add me as a collaborator to your forked repo and I can make the changes.

2018-07-24 07:16 UTC, kingmorning commented
ok，I added you as a collaborator to my forked repo, thank you for this help.
I tried to make the changes, but failed.
I'm not familiar with scala, especially the play framework.

2018-07-28 20:18 UTC, patelh approved these changes

2018-07-28 20:18 UTC, merged

2018-07-28 20:20 UTC, patelh commented
@kingmorning Version 1.3.3.21 has these changes, can you test it out on your cluster and then we can do a release.

2018-08-06 18:10 UTC, patelh commented
Yes

2018-08-08 22:27 UTC, TheMonolithX64 commented
@kingmorning @patelh Where can 1.3.3.21 be pulled from to build and try this out in a SSL-enabled cluster?

2019-02-18 18:35 UTC, TheMonolithX64 commented
I can confirm that build 1.3.3.21+ I can now see Kafka consumers listed in the UI using SSL-only enabled clusters. Tested on multiple secured clusters, two+ nodes w/ SSL client auth required.

2019-07-29 21:14 UTC, carlcauchigig commented
Hi, can you take a look at this issue: https://github.com/yahoo/kafka-manager/issues/664 as it might be similar

2023-08-14 22:49 UTC, Neustradamus commented
Linked to:
- https://github.com/scram-sasl/info/issues/1